{{- if and .Values.global.enabled .Values.web.enabled (not .Values.global.externalSecrets.enabled) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.global.projectName }}-secrets
  {{ if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{ else }}
  namespace: {{ .Release.Namespace }}
  {{ end }}
type: Opaque
data: {}
{{- end }}