apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartmuseum-auth.fullname" . }}
  labels:
    {{- include "chartmuseum-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    {{- include "chartmuseum-auth.selectorLabels" . | nindent 4 }}
